// Mocks generated by Mockito 5.2.0 from annotations
// in workout_zone/test/bloc/auth_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i4;
import 'package:workout_zone/models/user_model.dart' as _i3;
import 'package:workout_zone/services/locals/user_info_service.dart' as _i7;
import 'package:workout_zone/services/remotes/auth_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDio_0 extends _i1.Fake implements _i2.Dio {}

class _FakeUserModel_1 extends _i1.Fake implements _i3.UserModel {}

class _FakeSharedPreferences_2 extends _i1.Fake
    implements _i4.SharedPreferences {}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i5.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(Invocation.getter(#dio), returnValue: _FakeDio_0())
          as _i2.Dio);
  @override
  _i6.Future<_i3.UserModel> register(
          {String? name, String? email, String? phone, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(#register, [], {
                #name: name,
                #email: email,
                #phone: phone,
                #password: password
              }),
              returnValue: Future<_i3.UserModel>.value(_FakeUserModel_1()))
          as _i6.Future<_i3.UserModel>);
  @override
  _i6.Future<_i3.UserModel> login({String? email, String? password}) => (super
      .noSuchMethod(
          Invocation.method(#login, [], {#email: email, #password: password}),
          returnValue: Future<_i3.UserModel>.value(_FakeUserModel_1())) as _i6
      .Future<_i3.UserModel>);
  @override
  _i6.Future<_i3.UserModel> verifyEmail({String? email}) =>
      (super.noSuchMethod(Invocation.method(#verifyEmail, [], {#email: email}),
              returnValue: Future<_i3.UserModel>.value(_FakeUserModel_1()))
          as _i6.Future<_i3.UserModel>);
  @override
  _i6.Future<_i3.UserModel> resetPassword({String? email, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #resetPassword, [], {#email: email, #password: password}),
              returnValue: Future<_i3.UserModel>.value(_FakeUserModel_1()))
          as _i6.Future<_i3.UserModel>);
}

/// A class which mocks [UserInfoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserInfoService extends _i1.Mock implements _i7.UserInfoService {
  MockUserInfoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.SharedPreferences get sharedPreferences =>
      (super.noSuchMethod(Invocation.getter(#sharedPreferences),
          returnValue: _FakeSharedPreferences_2()) as _i4.SharedPreferences);
  @override
  _i3.UserModel getUserInfo() =>
      (super.noSuchMethod(Invocation.method(#getUserInfo, []),
          returnValue: _FakeUserModel_1()) as _i3.UserModel);
  @override
  _i6.Future<void> updateUserInfo(
          {String? token,
          bool? hasLogin,
          int? id,
          String? name,
          String? email,
          String? phone,
          String? password,
          String? memberType}) =>
      (super.noSuchMethod(
          Invocation.method(#updateUserInfo, [], {
            #token: token,
            #hasLogin: hasLogin,
            #id: id,
            #name: name,
            #email: email,
            #phone: phone,
            #password: password,
            #memberType: memberType
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> resetUserInfo() =>
      (super.noSuchMethod(Invocation.method(#resetUserInfo, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
}
